version: '3.7'
services:
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - postgres
  spirity-api:
    container_name: rte-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - port=${BACKEND_PORT}
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres


volumes:
  postgres:
    name: spirity-db

networks:
  postgres:
    driver: bridge