version: '3.7'
services:
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - postgres
  spirity-api:
    container_name: rte-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - port=${BACKEND_PORT}
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@spirity.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - postgres
    depends_on:
      - postgres


volumes:
  postgres:
    name: spirity-db
  pgadmin:

networks:
  postgres:
    driver: bridge